
eval "$(/opt/homebrew/bin/brew shellenv)"


# Added by Toolbox App
export PATH="$PATH:/Users/martino/Library/Application Support/JetBrains/Toolbox/scripts"


# Created by `pipx` on 2024-10-25 06:17:10
export PATH="$PATH:/Users/martino/.local/bin"
