export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export GPG_TTY=$(tty)
export ENABLE_LSP_TOOLS=1

# PATH additions
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="$PATH:$HOME/.dotnet/tools"

# Cargo
. "$HOME/.cargo/env"
