# Add autoloadable functions to fpath
fpath=(~/.zsh-functions $fpath)
autoload -Uz grb _git_branch_worktree gfeature gfix gchore gwt _gwt md2pdf _dotnet_zsh_complete

# Source all modules
for conf in ~/.zshrc.d/*.zsh; do
  source "$conf"
done
