" Auto-install vim-plug if not present.
let data_dir = '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo ' . data_dir . '/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins.
call plug#begin()
Plug 'EdenEast/nightfox.nvim'
call plug#end()

" Sets the default vim settings.
source $VIMRUNTIME/defaults.vim

" Enable syntax highlighting.
syntax on

" Enable true color support.
if has('termguicolors')
  set termguicolors
endif

" Color scheme.
silent! colorscheme nightfox
