" Auto-install vim-plug if not present.
let data_dir = '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo ' . data_dir . '/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins.
call plug#begin()
Plug 'EdenEast/nightfox.nvim'
call plug#end()

" Sets the default vim settings.
source $VIMRUNTIME/defaults.vim

" Enable syntax highlighting.
syntax on

" Enable true color support.
if has('termguicolors')
  set termguicolors
endif

" Color scheme.
silent! colorscheme nightfox

" Line numbers.
set number

" Search.
set hlsearch
set ignorecase
set smartcase

" Indentation (2-space, spaces not tabs).
set expandtab
set shiftwidth=2
set tabstop=2
set smartindent

" Splits open below and to the right.
set splitbelow
set splitright

" Persistent undo across sessions.
set undofile
set undodir=~/.vim/undodir

" Highlight current line.
set cursorline

" Use system clipboard.
set clipboard=unnamedplus
